# Урок 2. Матрицы и матричные операции

## Матрицы и матричные операции. Часть 1

In [1]:
import numpy as np
import math
import copy

In [2]:
def generate_matrix(n, m, min_value=0, max_value=9):
    try:
        return np.random.randint(min_value, max_value+1, (n, m))
    except Exception as e:
        return e

def check(A, B):
    try:
        if len(A[0]) == len(B):
            return True
        else:
            return False
    except Exception as e:
        print(f'Exception: {e}')
        return False
    

#### __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

In [3]:
# а)

A = generate_matrix(4, 2)
B = generate_matrix(4, 2)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    

A:
[[5 5]
 [4 5]
 [4 2]
 [8 0]]

B:
[[7 9]
 [0 6]
 [7 2]
 [3 8]]

Произведение матриц A x B не определено.

Произведение матриц A x B не определено.



In [4]:
# б)

A = generate_matrix(2, 5)
B = generate_matrix(5, 3)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    

A:
[[8 4 4 4 7]
 [0 6 2 0 0]]

B:
[[4 6 2]
 [3 9 0]
 [1 7 4]
 [8 7 4]
 [6 5 1]]

A x B:
[[122 175  55]
 [ 20  68   8]]

Произведение матриц A x B не определено.



In [5]:
# в)

A = generate_matrix(8, 3)
B = generate_matrix(3, 8)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    

A:
[[4 4 0]
 [9 1 1]
 [1 5 4]
 [8 4 4]
 [6 7 3]
 [5 0 0]
 [8 2 6]
 [8 2 9]]

B:
[[1 9 7 8 9 0 0 0]
 [7 9 9 5 2 9 5 5]
 [9 9 2 6 9 3 4 6]]

A x B:
[[ 32  72  64  52  44  36  20  20]
 [ 25  99  74  83  92  12   9  11]
 [ 72  90  60  57  55  57  41  49]
 [ 72 144 100 108 116  48  36  44]
 [ 82 144 111 101  95  72  47  53]
 [  5  45  35  40  45   0   0   0]
 [ 76 144  86 110 130  36  34  46]
 [103 171  92 128 157  45  46  64]]

B x A:
[[210 143  96]
 [295 136 146]
 [316 162 146]]



In [6]:
# г)

A = generate_matrix(4, 4)
B = generate_matrix(4, 4)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    

A:
[[5 3 8 6]
 [1 6 8 5]
 [8 2 0 5]
 [0 4 6 5]]

B:
[[4 7 7 0]
 [6 0 0 3]
 [7 4 2 3]
 [3 7 8 9]]

A x B:
[[112 109  99  87]
 [111  74  63  87]
 [ 59  91  96  51]
 [ 81  59  52  75]]

B x A:
[[ 83  68  88  94]
 [ 30  30  66  51]
 [ 55  61 106  87]
 [ 86 103 134 138]]



#### __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [7]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

print(f'A + B:\n{A + B}\n')
print(f'A x B:\n{np.dot(A, B)}\n')
print(f'B x A:\n{np.dot(B, A)}\n')


A:
[[ 1 -2]
 [ 3  0]]

B:
[[ 4 -1]
 [ 0  5]]

A + B:
[[ 5 -3]
 [ 3  5]]

A x B:
[[  4 -11]
 [ 12  -3]]

B x A:
[[ 1 -8]
 [15  0]]



#### __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [8]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')
print(f'C:\n{C}\n')

print(f'3A - 2B + 4C:\n{3 * A - 2 * B + 4 * C}\n')


A:
[[ 1  7]
 [ 3 -6]]

B:
[[ 0  5]
 [ 2 -1]]

C:
[[ 2 -4]
 [ 1  1]]

3A - 2B + 4C:
[[ 11  -5]
 [  9 -12]]



#### __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [9]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'A:\n{A}\n')
print(f'A.T:\n{A.T}\n')

print(f'A x A.T:\n{np.dot(A, A.T)}\n')
print(f'A.T x A:\n{np.dot(A.T, A)}\n')


A:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

A.T:
[[ 4  5  2]
 [ 1 -2  3]]

A x A.T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A.T x A:
[[45  0]
 [ 0 14]]



#### __5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [10]:
def generate_array(n, m, min_value=0, max_value=9):
    try:
        return [[np.random.randint(min_value, max_value+1) for _ in range(m)] for _ in range(n)]
    except Exception as e:
        return e

def matrix_product(A, B):
    try:
        C = generate_array(len(A), len(B[0]), 0, 0)
        for i in range(len(A)):  
            for j in range(len(B[0])): 
                for k in range(len(B)): 
                    C[i][j] += A[i][k] * B[k][j]
        return C
    except Exception as e:
        return e


In [11]:
n, m, k = 2, 4, 2

A = generate_array(n, m)
B = generate_array(m, k)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'Trial(A x B):\n{matrix_product(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')

if check(A, B):
    print(f'Check(A x B):\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')


A:
[[1, 4, 5, 3], [6, 1, 3, 3]]

B:
[[1, 4], [7, 9], [0, 2], [9, 3]]

Trial(A x B):
[[56, 59], [40, 48]]

Check(A x B):
[[56 59]
 [40 48]]



## Матрицы и матричные операции. Часть 2

In [12]:
def matrix_determinant_2x2_3x3(A):
    try:
        if len(A) == len(A[0]):
            if len(A) == 2:
                det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
                return det
            elif len(A) == 3:
                det = (
                    A[0][0] * A[1][1] * A[2][2] +
                    A[0][1] * A[1][2] * A[2][0] +
                    A[0][2] * A[1][0] * A[2][1] -
                    A[0][2] * A[1][1] * A[2][0] -
                    A[0][1] * A[1][0] * A[2][2] -
                    A[0][0] * A[1][2] * A[2][1]
                )
                return det
            else:
                return 'Only 2x2 or 3x3 matricies'
        else:
            return 'Determinant is not defined'
    except Exception as e:
        return e
    

#### __1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [13]:
# а)

x = math.pi / 4

A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Trial(det(A)): 1.0000000000000002

Check(det(A)): 1.0



In [14]:
# б)

A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[4 2 3]
 [0 5 1]
 [0 0 9]]

Trial(det(A)): 180

Check(det(A)): 180.0



In [15]:
# в)

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Trial(det(A)): 0

Check(det(A)): -9.51619735392994e-16



#### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

In [16]:
A = np.array([[1, -2], [1, 2]])

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0



а) $det(A^{2})$:

$det(A) = 4$<br>

$A^{2}$ = $A x A$<br>
$det(A x B)$ = $det(A) * det(B)$<br>
$det(A^{2})$ = $det(A x A)$ = $det(A) * det(A)$<br>
$det(A^{2})$ = $4 * 4$ = $16$<br>

In [17]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A^2:\n{np.dot(A, A)}\n')
print(f'det(A^2): {np.linalg.det(np.dot(A, A))}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

A^2:
[[-1 -6]
 [ 3  2]]

det(A^2): 16.000000000000007



б) $det(A^{T})$:

$det(A) = 4$<br>

$det(A)$ = $det(A^{T})$<br>
$det(A^{T})$ = $det(A)$ = $4$<br>

In [18]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A:\n{A.T}\n')
print(f'det(A.T): {np.linalg.det(A.T)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

A:
[[ 1  1]
 [-2  2]]

det(A.T): 4.0



в) $det(2A)$:

$det(A) = 4$<br>

$det(kA)$ = $k^{n}det(A)$, где n - кол-во строк (столбцов) квадратной матрицы A размера n x n<br>
$det(2A)$ = $k^{n}det(A)$ = $2^{n} * 4$ = $2^{n+2}$<br>

In [19]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'2A:\n{np.dot(2, A)}\n')
print(f'det(2A): {2**(A.shape[0] + 2)}\n')
print(f'det(2A): {np.linalg.det(2 * A)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

2A:
[[ 2 -4]
 [ 2  4]]

det(2A): 16

det(2A): 15.999999999999998



#### __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

1) Если $det(A) = 0$, то матрица A вырождена.<br>
2) Если, как минимум, две строки матрицы A линейно зависимы, то матрица A вырождена.<br>

In [20]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'A:\n{A}\n')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]



In [21]:
# 1)

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det( A)}\n')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

det(A): 0.0



In [22]:
# 2)

print(f'A:\n{A}\n')
print(f'Умножим первую строку матрицы A на -2:')
print(f'-2{A[0]} = {A[1]}\n')
print(f'В результате умножения получаем вторую строку матрицы A:')
print(f'{-2 * A[0]} = {A[1]}')
print(f'Вторая строка матрицы A является линейной комбинацией первой строки матрицы A.')
print(f'Первая и вторая строки матрицы A линейнозависимы.')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

Умножим первую строку матрицы A на -2:
-2[-2  7 -3] = [  4 -14   6]

В результате умножения получаем вторую строку матрицы A:
[  4 -14   6] = [  4 -14   6]
Вторая строка матрицы A является линейной комбинацией первой строки матрицы A.
Первая и вторая строки матрицы A линейнозависимы.


#### __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Определение__

_Строчным рангом матрицы_ называется максимальное число линейно независимых строк этой матрицы.

_Столбцовым рангом матрицы_ называется максимальное число линейно независимых столбцов этой матрицы.

__Теорема__

_Строчный ранг матрицы всегда совпадает с столбцовым и равен максимальному размеру ее невырожденного минора._

In [23]:
# а)

A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'A:\n{A}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]



In [24]:
print(f'A:\n{A}\n')
print(f'Сложим первую и вторую строки матрицы A:')
print(f'{A[0]} + {A[1]} = {A[0] + A[1]}\n')
print(f'В результате сложения получаем третью строку матрицы A:')
print(f'{A[2]}\n')
print(f'Третья строка матрицы A является линейной комбинацией первой и второй строк матрицы A.')
print(f'rank(A): 2\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

Сложим первую и вторую строки матрицы A:
[1 2 3] + [1 1 1] = [2 3 4]

В результате сложения получаем третью строку матрицы A:
[2 3 4]

Третья строка матрицы A является линейной комбинацией первой и второй строк матрицы A.
rank(A): 2



In [25]:
print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

rank(A): 2



In [26]:
# б)

A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'A:\n{A}\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]



In [27]:
print(f'A:\n{A}\n')
print(f'Вычтем из третьей строки вторую строку A:')
print(f'{A[2]} - {A[1]} = {A[2] - A[1]}\n')
print(f'В результате вычитания получаем первую строку матрицы A:')
print(f'{A[0]}\n')
print(f'Первая строка матрицы A является линейной комбинацией втрой и третьей строк матрицы A.')
print(f'rank(A): 3\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

Вычтем из третьей строки вторую строку A:
[0 0 4 3] - [0 0 2 2] = [0 0 2 1]

В результате вычитания получаем первую строку матрицы A:
[0 0 2 1]

Первая строка матрицы A является линейной комбинацией втрой и третьей строк матрицы A.
rank(A): 3



In [28]:
print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

rank(A): 3



#### __5*.__ Написать на Python функцию для нахождения определителя матрицы размера n x n, не используя NumPy.

In [29]:
def matrix_determinant(A):
    try:
        n = len(A)
        m = len(A[0])

        if n == m:            
            if n == 2:
                det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
                return det

            norms = []

            for row in A:
                norm = 0
                for col in row:
                    norm += math.sqrt(math.pow(col, 2))
                norms.append(norm)

            i = 0
            min_norm = norms[0]

            for idx, norm in enumerate(norms[1:], start=1):
                if norm < min_norm:
                    min_norm = norm
                    i = idx
            
            det = 0
            for j in range(m):
                M = [[col for cidx, col in enumerate(row) if cidx != j ] for ridx, row in enumerate(A) if ridx != i]
                sign = (-1) ** ((i + 1 + j + 1) % 2)
                det += sign * A[i][j] * matrix_determinant(M)
                
            return det
        else:
            return 'Determinant is not defined'
    except Exception as e:
        return e
    

In [30]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[4 2 3]
 [0 5 1]
 [0 0 9]]

Trial(det(A)): 180
Check(det(A)): 180.0


In [31]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Trial(det(A)): 0
Check(det(A)): -9.51619735392994e-16


In [32]:
A = np.array([[2, 5, 1, 3], [4, 1, 7, 9], [6, 8, 3, 2], [7, 8, 1, 4]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[2 5 1 3]
 [4 1 7 9]
 [6 8 3 2]
 [7 8 1 4]]

Trial(det(A)): 630
Check(det(A)): 630.0000000000001


In [38]:
def matrix_determinant_2x2_3x3(A):
    try:
        if len(A) == len(A[0]):
            if len(A) == 2:
                det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
                return det
            elif len(A) == 3:
                det = (
                    A[0][0] * A[1][1] * A[2][2] +
                    A[0][1] * A[1][2] * A[2][0] +
                    A[0][2] * A[1][0] * A[2][1] -
                    A[0][2] * A[1][1] * A[2][0] -
                    A[0][1] * A[1][0] * A[2][2] -
                    A[0][0] * A[1][2] * A[2][1]
                )
                return det
            else:
                return 'Only 2x2 or 3x3 matricies'
        else:
            return 'Determinant is not defined'
    except Exception as e:
        return e
    

#### __1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

# а)

x = math.pi / 4

A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

# б)

A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

# в)

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

#### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

A = np.array([[1, -2], [1, 2]])

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')

а) $det(A^{2})$:

$det(A) = 4$<br>

$A^{2}$ = $A x A$<br>
$det(A x B)$ = $det(A) * det(B)$<br>
$det(A^{2})$ = $det(A x A)$ = $det(A) * det(A)$<br>
$det(A^{2})$ = $4 * 4$ = $16$<br>

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A^2:\n{np.dot(A, A)}\n')
print(f'det(A^2): {np.linalg.det(np.dot(A, A))}\n')

б) $det(A^{T})$:

$det(A) = 4$<br>

$det(A)$ = $det(A^{T})$<br>
$det(A^{T})$ = $det(A)$ = $4$<br>

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A:\n{A.T}\n')
print(f'det(A.T): {np.linalg.det(A.T)}\n')

в) $det(2A)$:

$det(A) = 4$<br>

$det(kA)$ = $k^{n}det(A)$, где n - кол-во строк (столбцов) квадратной матрицы A размера n x n<br>
$det(2A)$ = $k^{n}det(A)$ = $2^{n} * 4$ = $2^{n+2}$<br>

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'2A:\n{np.dot(2, A)}\n')
print(f'det(2A): {2**(A.shape[0] + 2)}\n')
print(f'det(2A): {np.linalg.det(2 * A)}\n')

#### __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

1) Если $det(A) = 0$, то матрица A вырождена.<br>
2) Если, как минимум, две строки матрицы A линейно зависимы, то матрица A вырождена.<br>

A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'A:\n{A}\n')

# 1)

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det( A)}\n')

# 2)

print(f'A:\n{A}\n')
print(f'Умножим первую строку матрицы A на -2:')
print(f'-2{A[0]} = {A[1]}\n')
print(f'В результате умножения получаем вторую строку матрицы A:')
print(f'{-2 * A[0]} = {A[1]}')
print(f'Вторая строка матрицы A является линейной комбинацией первой строки матрицы A.')
print(f'Первая и вторая строки матрицы A линейнозависимы.')

#### __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Определение__

_Строчным рангом матрицы_ называется максимальное число линейно независимых строк этой матрицы.

_Столбцовым рангом матрицы_ называется максимальное число линейно независимых столбцов этой матрицы.

__Теорема__

_Строчный ранг матрицы всегда совпадает с столбцовым и равен максимальному размеру ее невырожденного минора._

# а)

A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'A:\n{A}\n')

print(f'A:\n{A}\n')
print(f'Сложим первую и вторую строки матрицы A:')
print(f'{A[0]} + {A[1]} = {A[0] + A[1]}\n')
print(f'В результате сложения получаем третью строку матрицы A:')
print(f'{A[2]}\n')
print(f'Третья строка матрицы A является линейной комбинацией первой и второй строк матрицы A.')
print(f'rank(A): 2\n')

print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

# б)

A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'A:\n{A}\n')

print(f'A:\n{A}\n')
print(f'Вычтем из третьей строки вторую строку A:')
print(f'{A[2]} - {A[1]} = {A[2] - A[1]}\n')
print(f'В результате вычитания получаем первую строку матрицы A:')
print(f'{A[0]}\n')
print(f'Первая строка матрицы A является линейной комбинацией втрой и третьей строк матрицы A.')
print(f'rank(A): 3\n')

print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

#### __5*.__ Написать на Python функцию для нахождения определителя матрицы размера n x n, не используя NumPy.

def matrix_determinant(A):
    try:
        n = len(A)
        m = len(A[0])

        if n == m:            
            if n == 2:
                det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
                return det

            norms = []

            for row in A:
                norm = 0
                for col in row:
                    norm += math.sqrt(math.pow(col, 2))
                norms.append(norm)
вввв
            i = 0
            min_norm = norms[0]

            for idx, norm in enumerate(norms[1:], start=1):
                if norm < min_norm:
                    min_norm = norm
                    i = idx
            
            det = 0
            for j in range(m):
                M = [[col for cidx, col in enumerate(row) if cidx != j ] for ridx, row in enumerate(A) if ridx != i]
                sign = (-1) ** ((i + 1 + j + 1) % 2)
                det += sign * A[i][j] * matrix_determinant(M)
                
            return det
        else:
            return 'Determinant is not defined'
    except Exception as e:
        return e
    

A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A = np.array([[2, 5, 1, 3], [4, 1, 7, 9], [6, 8, 3, 2], [7, 8, 1, 4]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')



IndentationError: unindent does not match any outer indentation level (<tokenize>, line 27)

In [33]:
def matrix_determinant_2x2_3x3(A):
    try:
        if len(A) == len(A[0]):
            if len(A) == 2:
                det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
                return det
            elif len(A) == 3:
                det = (
                    A[0][0] * A[1][1] * A[2][2] +
                    A[0][1] * A[1][2] * A[2][0] +
                    A[0][2] * A[1][0] * A[2][1] -
                    A[0][2] * A[1][1] * A[2][0] -
                    A[0][1] * A[1][0] * A[2][2] -
                    A[0][0] * A[1][2] * A[2][1]
                )
                return det
            else:
                return 'Only 2x2 or 3x3 matricies'
        else:
            return 'Determinant is not defined'
    except Exception as e:
        return e
    

#### __1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [34]:
# а)

x = math.pi / 4

A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Trial(det(A)): 1.0000000000000002

Check(det(A)): 1.0



In [35]:
# б)

A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[4 2 3]
 [0 5 1]
 [0 0 9]]

Trial(det(A)): 180

Check(det(A)): 180.0



In [36]:
# в)

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Trial(det(A)): 0

Check(det(A)): -9.51619735392994e-16



#### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

In [37]:
A = np.array([[1, -2], [1, 2]])

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0



а) $det(A^{2})$:

$det(A) = 4$<br>

$A^{2}$ = $A x A$<br>
$det(A x B)$ = $det(A) * det(B)$<br>
$det(A^{2})$ = $det(A x A)$ = $det(A) * det(A)$<br>
$det(A^{2})$ = $4 * 4$ = $16$<br>

In [38]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A^2:\n{np.dot(A, A)}\n')
print(f'det(A^2): {np.linalg.det(np.dot(A, A))}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

A^2:
[[-1 -6]
 [ 3  2]]

det(A^2): 16.000000000000007



б) $det(A^{T})$:

$det(A) = 4$<br>

$det(A)$ = $det(A^{T})$<br>
$det(A^{T})$ = $det(A)$ = $4$<br>

In [39]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A:\n{A.T}\n')
print(f'det(A.T): {np.linalg.det(A.T)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

A:
[[ 1  1]
 [-2  2]]

det(A.T): 4.0



в) $det(2A)$:

$det(A) = 4$<br>

$det(kA)$ = $k^{n}det(A)$, где n - кол-во строк (столбцов) квадратной матрицы A размера n x n<br>
$det(2A)$ = $k^{n}det(A)$ = $2^{n} * 4$ = $2^{n+2}$<br>

In [40]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'2A:\n{np.dot(2, A)}\n')
print(f'det(2A): {2**(A.shape[0] + 2)}\n')
print(f'det(2A): {np.linalg.det(2 * A)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

2A:
[[ 2 -4]
 [ 2  4]]

det(2A): 16

det(2A): 15.999999999999998



#### __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

1) Если $det(A) = 0$, то матрица A вырождена.<br>
2) Если, как минимум, две строки матрицы A линейно зависимы, то матрица A вырождена.<br>

In [41]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'A:\n{A}\n')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]



In [42]:
# 1)

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det( A)}\n')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

det(A): 0.0



In [43]:
# 2)

print(f'A:\n{A}\n')
print(f'Умножим первую строку матрицы A на -2:')
print(f'-2{A[0]} = {A[1]}\n')
print(f'В результате умножения получаем вторую строку матрицы A:')
print(f'{-2 * A[0]} = {A[1]}')
print(f'Вторая строка матрицы A является линейной комбинацией первой строки матрицы A.')
print(f'Первая и вторая строки матрицы A линейнозависимы.')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

Умножим первую строку матрицы A на -2:
-2[-2  7 -3] = [  4 -14   6]

В результате умножения получаем вторую строку матрицы A:
[  4 -14   6] = [  4 -14   6]
Вторая строка матрицы A является линейной комбинацией первой строки матрицы A.
Первая и вторая строки матрицы A линейнозависимы.


#### __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Определение__

_Строчным рангом матрицы_ называется максимальное число линейно независимых строк этой матрицы.

_Столбцовым рангом матрицы_ называется максимальное число линейно независимых столбцов этой матрицы.

__Теорема__

_Строчный ранг матрицы всегда совпадает с столбцовым и равен максимальному размеру ее невырожденного минора._

In [44]:
# а)

A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'A:\n{A}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]



In [45]:
print(f'A:\n{A}\n')
print(f'Сложим первую и вторую строки матрицы A:')
print(f'{A[0]} + {A[1]} = {A[0] + A[1]}\n')
print(f'В результате сложения получаем третью строку матрицы A:')
print(f'{A[2]}\n')
print(f'Третья строка матрицы A является линейной комбинацией первой и второй строк матрицы A.')
print(f'rank(A): 2\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

Сложим первую и вторую строки матрицы A:
[1 2 3] + [1 1 1] = [2 3 4]

В результате сложения получаем третью строку матрицы A:
[2 3 4]

Третья строка матрицы A является линейной комбинацией первой и второй строк матрицы A.
rank(A): 2



In [46]:
print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

rank(A): 2



In [47]:
# б)

A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'A:\n{A}\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]



In [48]:
print(f'A:\n{A}\n')
print(f'Вычтем из третьей строки вторую строку A:')
print(f'{A[2]} - {A[1]} = {A[2] - A[1]}\n')
print(f'В результате вычитания получаем первую строку матрицы A:')
print(f'{A[0]}\n')
print(f'Первая строка матрицы A является линейной комбинацией втрой и третьей строк матрицы A.')
print(f'rank(A): 3\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

Вычтем из третьей строки вторую строку A:
[0 0 4 3] - [0 0 2 2] = [0 0 2 1]

В результате вычитания получаем первую строку матрицы A:
[0 0 2 1]

Первая строка матрицы A является линейной комбинацией втрой и третьей строк матрицы A.
rank(A): 3



In [49]:
print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

rank(A): 3



#### __5*.__ Написать на Python функцию для нахождения определителя матрицы размера n x n, не используя NumPy.

In [50]:
def matrix_determinant(A):
    try:
        n = len(A)
        m = len(A[0])

        if n == m:            
            if n == 2:
                det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
                return det

            norms = []

            for row in A:
                norm = 0
                for col in row:
                    norm += math.sqrt(math.pow(col, 2))
                norms.append(norm)

            i = 0
            min_norm = norms[0]

            for idx, norm in enumerate(norms[1:], start=1):
                if norm < min_norm:
                    min_norm = norm
                    i = idx
            
            det = 0
            for j in range(m):
                M = [[col for cidx, col in enumerate(row) if cidx != j ] for ridx, row in enumerate(A) if ridx != i]
                sign = (-1) ** ((i + 1 + j + 1) % 2)
                det += sign * A[i][j] * matrix_determinant(M)
                
            return det
        else:
            return 'Determinant is not defined'
    except Exception as e:
        return e
    

In [51]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[4 2 3]
 [0 5 1]
 [0 0 9]]

Trial(det(A)): 180
Check(det(A)): 180.0


In [52]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Trial(det(A)): 0
Check(det(A)): -9.51619735392994e-16


In [53]:
A = np.array([[2, 5, 1, 3], [4, 1, 7, 9], [6, 8, 3, 2], [7, 8, 1, 4]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[2 5 1 3]
 [4 1 7 9]
 [6 8 3 2]
 [7 8 1 4]]

Trial(det(A)): 630
Check(det(A)): 630.0000000000001


## Матрицы и матричные операции. Часть 2

In [56]:
def matrix_determinant_2x2_3x3(A):
    try:
        if len(A) == len(A[0]):
            if len(A) == 2:
                det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
                return det
            elif len(A) == 3:
                det = (
                    A[0][0] * A[1][1] * A[2][2] +
                    A[0][1] * A[1][2] * A[2][0] +
                    A[0][2] * A[1][0] * A[2][1] -
                    A[0][2] * A[1][1] * A[2][0] -
                    A[0][1] * A[1][0] * A[2][2] -
                    A[0][0] * A[1][2] * A[2][1]
                )
                return det
            else:
                return 'Only 2x2 or 3x3 matricies'
        else:
            return 'Determinant is not defined'
    except Exception as e:
        return e
    

#### __1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [57]:
# а)

x = math.pi / 4

A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Trial(det(A)): 1.0000000000000002

Check(det(A)): 1.0



In [58]:
# б)

A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[4 2 3]
 [0 5 1]
 [0 0 9]]

Trial(det(A)): 180

Check(det(A)): 180.0



In [59]:
# в)

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Trial(det(A)): 0

Check(det(A)): -9.51619735392994e-16



#### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

In [60]:
A = np.array([[1, -2], [1, 2]])

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0



а) $det(A^{2})$:

$det(A) = 4$<br>

$A^{2}$ = $A x A$<br>
$det(A x B)$ = $det(A) * det(B)$<br>
$det(A^{2})$ = $det(A x A)$ = $det(A) * det(A)$<br>
$det(A^{2})$ = $4 * 4$ = $16$<br>

In [61]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A^2:\n{np.dot(A, A)}\n')
print(f'det(A^2): {np.linalg.det(np.dot(A, A))}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

A^2:
[[-1 -6]
 [ 3  2]]

det(A^2): 16.000000000000007



б) $det(A^{T})$:

$det(A) = 4$<br>

$det(A)$ = $det(A^{T})$<br>
$det(A^{T})$ = $det(A)$ = $4$<br>

In [62]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A:\n{A.T}\n')
print(f'det(A.T): {np.linalg.det(A.T)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

A:
[[ 1  1]
 [-2  2]]

det(A.T): 4.0



в) $det(2A)$:

$det(A) = 4$<br>

$det(kA)$ = $k^{n}det(A)$, где n - кол-во строк (столбцов) квадратной матрицы A размера n x n<br>
$det(2A)$ = $k^{n}det(A)$ = $2^{n} * 4$ = $2^{n+2}$<br>

In [63]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'2A:\n{np.dot(2, A)}\n')
print(f'det(2A): {2**(A.shape[0] + 2)}\n')
print(f'det(2A): {np.linalg.det(2 * A)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

2A:
[[ 2 -4]
 [ 2  4]]

det(2A): 16

det(2A): 15.999999999999998



#### __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

1) Если $det(A) = 0$, то матрица A вырождена.<br>
2) Если, как минимум, две строки матрицы A линейно зависимы, то матрица A вырождена.<br>

In [64]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'A:\n{A}\n')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]



In [11]:
# 1)

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det( A)}\n')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

det(A): 0.0



In [12]:
# 2)

print(f'A:\n{A}\n')
print(f'Умножим первую строку матрицы A на -2:')
print(f'-2{A[0]} = {A[1]}\n')
print(f'В результате умножения получаем вторую строку матрицы A:')
print(f'{-2 * A[0]} = {A[1]}')
print(f'Вторая строка матрицы A является линейной комбинацией первой строки матрицы A.')
print(f'Первая и вторая строки матрицы A линейнозависимы.')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

Умножим первую строку матрицы A на -2:
-2[-2  7 -3] = [  4 -14   6]

В результате умножения получаем вторую строку матрицы A:
[  4 -14   6] = [  4 -14   6]
Вторая строка матрицы A является линейной комбинацией первой строки матрицы A.
Первая и вторая строки матрицы A линейнозависимы.


#### __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Определение__

_Строчным рангом матрицы_ называется максимальное число линейно независимых строк этой матрицы.

_Столбцовым рангом матрицы_ называется максимальное число линейно независимых столбцов этой матрицы.

__Теорема__

_Строчный ранг матрицы всегда совпадает с столбцовым и равен максимальному размеру ее невырожденного минора._

In [13]:
# а)

A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'A:\n{A}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]



In [14]:
print(f'A:\n{A}\n')
print(f'Сложим первую и вторую строки матрицы A:')
print(f'{A[0]} + {A[1]} = {A[0] + A[1]}\n')
print(f'В результате сложения получаем третью строку матрицы A:')
print(f'{A[2]}\n')
print(f'Третья строка матрицы A является линейной комбинацией первой и второй строк матрицы A.')
print(f'rank(A): 2\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

Сложим первую и вторую строки матрицы A:
[1 2 3] + [1 1 1] = [2 3 4]

В результате сложения получаем третью строку матрицы A:
[2 3 4]

Третья строка матрицы A является линейной комбинацией первой и второй строк матрицы A.
rank(A): 2



In [15]:
print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

rank(A): 2



In [16]:
# б)

A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'A:\n{A}\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]



In [17]:
print(f'A:\n{A}\n')
print(f'Вычтем из третьей строки вторую строку A:')
print(f'{A[2]} - {A[1]} = {A[2] - A[1]}\n')
print(f'В результате вычитания получаем первую строку матрицы A:')
print(f'{A[0]}\n')
print(f'Первая строка матрицы A является линейной комбинацией втрой и третьей строк матрицы A.')
print(f'rank(A): 3\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

Вычтем из третьей строки вторую строку A:
[0 0 4 3] - [0 0 2 2] = [0 0 2 1]

В результате вычитания получаем первую строку матрицы A:
[0 0 2 1]

Первая строка матрицы A является линейной комбинацией втрой и третьей строк матрицы A.
rank(A): 3



In [18]:
print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

rank(A): 3



#### __5*.__ Написать на Python функцию для нахождения определителя матрицы размера n x n, не используя NumPy.

In [19]:
def matrix_determinant(A):
    try:
        n = len(A)
        m = len(A[0])

        if n == m:            
            if n == 2:
                det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
                return det

            norms = []

            for row in A:
                norm = 0
                for col in row:
                    norm += math.sqrt(math.pow(col, 2))
                norms.append(norm)

            i = 0
            min_norm = norms[0]

            for idx, norm in enumerate(norms[1:], start=1):
                if norm < min_norm:
                    min_norm = norm
                    i = idx
            
            det = 0
            for j in range(m):
                M = [[col for cidx, col in enumerate(row) if cidx != j ] for ridx, row in enumerate(A) if ridx != i]
                sign = (-1) ** ((i + 1 + j + 1) % 2)
                det += sign * A[i][j] * matrix_determinant(M)
                
            return det
        else:
            return 'Determinant is not defined'
    except Exception as e:
        return e
    

In [20]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[4 2 3]
 [0 5 1]
 [0 0 9]]

Trial(det(A)): 180
Check(det(A)): 180.0


In [21]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Trial(det(A)): 0
Check(det(A)): -9.51619735392994e-16


In [22]:
A = np.array([[2, 5, 1, 3], [4, 1, 7, 9], [6, 8, 3, 2], [7, 8, 1, 4]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[2 5 1 3]
 [4 1 7 9]
 [6 8 3 2]
 [7 8 1 4]]

Trial(det(A)): 630
Check(det(A)): 630.0000000000001
