# Урок 4. Системы линейных уравненийм

## Системы линейных уравнений. Часть 1

In [2]:
import numpy as np
import scipy.linalg

#### __1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Запишем систему в виде расширенной матрицы.<br>

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$

Умножим 1 строку на -2 и сложим со 2 строкой.<br>
Умножим 1 строку на -1 и сложим с 3 строкой.<br>

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$

Разделим каждую строку матрицы на соответсвующий ведущий элемент: 1 строку на 1, 2 строку на -2, 3 строку на -2.<br>

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & 1 & -1 & -5 \\ 
0 & 0 & 2 & -\frac{3}{2}
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
-2
\end{matrix}
\end{pmatrix}.$

Выразим $x_{1}, x_{2}, x_{3}$ относительно остальных переменных.<br>

$x_{1} = -x_{2} + x_{3} + 2x_{4}$<br>
$x_{2} = 2 + x_{3} + 5x_{4}$<br>
$x_{3} = -2 + \frac{3}{2}x_{4}$<br>

Решение:<br>
$x_{1} = -2 - 3x_{4}$<br>
$x_{2} = \frac{13}{2}x_{4}$<br>
$x_{3} = -2 + \frac{3}{2}x_{4}$<br>
$x_{4}$ - произвольное действительное число<br>

Частное решение:<br>
$x_{1} = -2$<br>
$x_{2} = 0$<br>
$x_{3} = -2$<br>
$x_{4} = 0$<br>

#### __2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

__Теорема__ 

Необходимым и достаточным условием совместности системы из $m$ уравнений с $n$ неизвестными является равенство между собой рангов матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$

$$rank A=rank \tilde A.$$

Причем:<br>
1) если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, т. е. имеет единственное решение;<br>
2) если $rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>
3) если $rankA<rank \tilde A$, то система несовместна.

In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]

A_ext:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]

rank(A): 3

rank(A_ext): 3

# of vars: 3

Система имеет единственное решение.


In [3]:
A = np.array([[3, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 3 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]

A_ext:
[[ 3 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]

rank(A): 2

rank(A_ext): 3

# of vars: 3

Система несовместна.


In [4]:
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 1  2  5]
 [ 3  1 -8]]

A_ext:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]

rank(A): 2

rank(A_ext): 2

# of vars: 3

Система имеет бесконечное кол-во решений.


#### __3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [5]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]

A_ext:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]

rank(A): 4

rank(A_ext): 4

# of vars: 4

Система имеет единственное решение.


#### __4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Запишем систему в виде расширенной матрицы.<br>

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$

1 строку умножим на 2 и вычтем и 2 строки.<br>
1 строку умножим на 3 и вычтем и 3 строки.<br>

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
2 & 1 & 0 \\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c - 3a
\end{matrix}
\end{pmatrix}.$

2 строку умножим на 2 и вычтем из 3 строки. <br>

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
2 & 1 & 0 \\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c - 3a - 2b
\end{matrix}
\end{pmatrix}.$

Если c - 3a - 2b != 0, то система несовместна.<br>

## Системы линейных уравнений. Часть 2

#### __1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [2]:
# а)

A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])

det_A = np.linalg.det(A)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')

print(f'det(A): {det_A}\n')

if det_A != 0:
    print(f'Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.\n')

A1 = np.column_stack([b, A[:, 1]])
det_A1 = np.linalg.det(A1)

print(f'A1:\n{A1}\n')
print(f'det(A1): {det_A1}\n')

A2 = np.column_stack([A[:, 0], b])
det_A2 = np.linalg.det(A2)

print(f'A2:\n{A2}\n')
print(f'det(A2): {det_A2}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')

A:
[[ 1 -2]
 [ 3 -4]]

b:
[1 7]

det(A): 2.0000000000000004

Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.

A1:
[[ 1 -2]
 [ 7 -4]]

det(A1): 9.999999999999998

A2:
[[1 1]
 [3 7]]

det(A2): 4.0

x1 = 4.999999999999998
x2 = 1.9999999999999996


In [3]:
# б)

A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])

det_A = np.linalg.det(A)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')

print(f'det(A): {det_A}\n')

if det_A != 0:
    print(f'Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.\n')

A1 = np.column_stack([b, A[:, 1:]])
det_A1 = np.linalg.det(A1)

print(f'A1:\n{A1}\n')
print(f'det(A1): {det_A1}\n')

A2 = np.column_stack([A[:, 0], b, A[:, 2]])
det_A2 = np.linalg.det(A2)

print(f'A2:\n{A2}\n')
print(f'det(A2): {det_A2}\n')

A3 = np.column_stack([A[:, 0:2], b])
det_A3 = np.linalg.det(A3)

print(f'A3:\n{A3}\n')
print(f'det(A3): {det_A3}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')
print(f'x3 = {det_A3 / det_A}')

A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

b:
[10 -2  1]

det(A): 42.99999999999998

Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.

A1:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]

det(A1): 86.00000000000004

A2:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]

det(A2): -43.000000000000014

A3:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]

det(A3): 42.99999999999998

x1 = 2.0000000000000018
x2 = -1.0000000000000009
x3 = 1.0


#### __2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а)<br>

Матрица коэффициентов:<br>

$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

Умножим 1 строку на 2 и вычтем из 2 строки:<br>

Матрица U:<br>

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
I_{31} & I_{32} & 1
\end{pmatrix}$

Умножим 1 строку на 3 и вычтем из 3 строки:<br>

Матрица U:<br>

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & I_{32} & 1
\end{pmatrix}$

Умножим 2 строку на 4 и вычтем из 3 строки:<br>

Матрица U:<br>

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

In [4]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
U = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])
L = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])

LU = np.dot(L, U)

print(f'A:\n{A}\n')
print(f'L:\n{L}\n')
print(f'U:\n{U}\n')
print(f'LU:\n{LU}\n')

A:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

L:
[[1 0 0]
 [2 1 0]
 [3 4 1]]

U:
[[1 2 4]
 [0 5 4]
 [0 0 2]]

LU:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]



б) <br>

Матрица коэффициентов:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
2 & 5 & 8 & 9 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}$

Умножим 1 строку на 2 и вычтем из 2 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
I_{31} & I_{32} & 1 & 0 \\
I_{41} & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 1 строку на 3 и вычтем из 3 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
4 & 22 & 53 & 33
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & I_{32} & 1 & 0 \\
I_{41} & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 1 строку на 4 и вычтем из 4 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
0 & 18 & 45 & 17
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & I_{32} & 1 & 0 \\
4 & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 2 строку на 5 и вычтем из 3 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 18 & 45 & 17
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 2 строку на 6 и вычтем из 4 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 21 & 11
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & I_{43} & 1
\end{pmatrix}$

Умножим 3 строку на 7 и вычтем из 4 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 0 & 4
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}$

In [5]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
U = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])
L = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])

LU = np.dot(L, U)

print(f'A:\n{A}\n')
print(f'L:\n{L}\n')
print(f'U:\n{U}\n')
print(f'LU:\n{LU}\n')

A:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]

L:
[[1 0 0 0]
 [2 1 0 0]
 [3 5 1 0]
 [4 6 7 1]]

U:
[[1 1 2 4]
 [0 3 4 1]
 [0 0 3 1]
 [0 0 0 4]]

LU:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]



#### __3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [6]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

A:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

b:
[ 1 -6 -5]

x:
[-1.00000000e+00  2.44249065e-16  1.00000000e+00]

Ax:
[ 1. -6. -5.]

Ax - b:
[0. 0. 0.]



#### __4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [7]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

K = scipy.linalg.cho_factor(A)
x = scipy.linalg.cho_solve(K, b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

b:
[ 531 -460  193]

x:
[ 6. -5. -4.]

Ax:
[ 531. -460.  193.]

Ax - b:
[0. 0. 0.]



#### __5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [8]:
def LU(A): 
  
    n = len(A)
    
    L = [[0 for _ in range(n)] for _ in range(n)]
    U = [[0 for _ in range(n)] for _ in range(n)] 
                  
    for i in range(n): 

        for k in range(i, n):  

            s = 0; 
            for j in range(i): 
                
                s += (L[i][j] * U[j][k]) 
  
            U[i][k] = A[i][k] - s
  
        for k in range(i, n): 
        
            if (i == k):
                
                L[i][i] = 1
                
            else:
                
                s = 0
                
                for j in range(i): 
                    
                    s += (L[k][j] * U[j][i])
  
                L[k][i] = int((A[k][i] - s) / U[i][i]) 
  
    return L, U


In [9]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])

L, U = LU(A)

print(f'A:\n{A}\n')
print(f'L:\n{np.array(L)}\n')
print(f'U:\n{np.array(U)}\n')
print(f'LU:\n{np.array(L) @ np.array(U)}\n')

A:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

L:
[[1 0 0]
 [2 1 0]
 [3 4 1]]

U:
[[1 2 4]
 [0 5 4]
 [0 0 2]]

LU:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

