# Урок 3. Линейные преобразования

In [1]:
import numpy as np

#### __1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [2]:
A = np.array([[-1, -6], [2, 6]])

print(f'A:\n{A}\n')

A:
[[-1 -6]
 [ 2  6]]



Для $n=2$

$$det(\textbf{A}-\lambda\textbf{I})=\begin{vmatrix}
a_{11}-\lambda & a_{12}\\ 
a_{21} & a_{22}-\lambda
\end{vmatrix} = \lambda^{2}-(a_{11}+a_{22})\lambda+(a_{11}a_{22}-a_{12}a_{21}).$$

$det(\textbf{A}-\lambda\textbf{I})$ = $0$<br>
$\lambda^{2} - (-1 + 6)\lambda + (-6 + 12)$ = $\lambda^{2} - 5\lambda + 6$ = $0$<br>
$D = b^{2} - 4ac$ = $(-5)^{2} - 4 * 1 * 6$ = $25 - 24$ = $1$<br>
$x_{1} = 2$<br>
$x_{2} = 3$<br>

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$

$\lambda = 2$<br>

$\begin{cases}
-x_{1}-6x_{2} = 2x_{1}, \\
2x_{1}+6x_{2} = 2x_{2}.
\end{cases}$

$\begin{cases}
3x_{1} = -6x_{2}, \\
2x_{2} = -x_{1} .
\end{cases}$

$\begin{cases}
x_{1} = -2x_{2}, \\
2x_{2} = -x_{1} .
\end{cases}$

$\begin{cases}
x_{1} = -2, \\
x_{2} = 1 .
\end{cases}$

v1 = (-2, 1)<br>

$\lambda = 3$<br>

$\begin{cases}
-x_{1}-6x_{2} = 3x_{1}, \\
2x_{1}+6x_{2} = 3x_{2}.
\end{cases}$

$\begin{cases}
4x_{1} = -6x_{2}, \\
2x_{1} = -3x_{2}.
\end{cases}$

$\begin{cases}
x_{1} = -\frac{3}{2}x_{2}, \\
x_{1} = -\frac{3}{2}x_{2}.
\end{cases}$

$\begin{cases}
x_{1} = \frac{3}{2}, \\
x_{2} = -1.
\end{cases}$

v2 = ($\frac{3}{2}$, -1)<br>

In [3]:
v1 = np.array([-2, 1])
v2 = np.array([3/2, -1])

n1 = np.linalg.norm(v1)
n2 = np.linalg.norm(v2)

print(f'A:\n{A}\n')
print(f'Собственные значения:\n{np.array([2, 3])}\n')
print(f'Собственные векторы:\n{v1}, {v2}\n')
print(f'Нормированные собственные векторы:\n{v1/n1}, {v2/n2}\n')

A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2 3]

Собственные векторы:
[-2  1], [ 1.5 -1. ]

Нормированные собственные векторы:
[-0.89442719  0.4472136 ], [ 0.83205029 -0.5547002 ]



In [4]:
w, v = np.linalg.eig(A)

print(f'A:\n{A}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v[:, 0]}, {v[:, 1]}\n')

A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2. 3.]

Собственные векторы:
[-0.89442719  0.4472136 ], [ 0.83205029 -0.5547002 ]



#### __2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

In [5]:
A = np.array([[-1, 0], [0, -1]])

print(f'A:\n{A}\n')

A:
[[-1  0]
 [ 0 -1]]



In [6]:
w, v = np.linalg.eig(A)

print(f'A:\n{A}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v[:, 0]}, {v[:, 1]}\n')

A:
[[-1  0]
 [ 0 -1]]

Собственные значения:
[-1. -1.]

Собственные векторы:
[1. 0.], [0. 1.]



Собственным вектором линейного оператора A (матрицы A) называется ненулевой вектор x такой, что Ax = λx.<br>
Для единичной матрицы E любой вектор x является собственным, с собственным числом, равным 1, так как Ex = x.<br>
Так как матрица A диагональная, тогда собственные значения: $\lambda_{1} = -1, \lambda_{2} =-1$.<br>
$A$ = $-1E$<br>
$-1Ex$ = $\lambda x$<br>
$-1x$ = $\lambda x$<br>
$\lambda$ = $-1$<br>
Таким образом, любой ненулевой вектор $x$ является собственным для линейного оператора $A$ = $-1E$.

In [7]:
# проверим на практике с помощью метода Монте-Карло:

x = np.array([np.random.randint(1, 999), np.random.randint(1, 999)])

trials = []

n = 100000

for _ in range(n):
    trial = np.array_equal(np.dot(A, x), -1 * x)
    trials.append(trial)
    
print(np.sum(trials) / n)

1.0


#### __3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$

$\begin{cases}
1 + 1 = 1\cdot\lambda \\ 
-1 + 3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$

Ответ: вектор $𝑥=(1,1)$ является собственным вектором линейного оператора A, а его собственное значения составляет $\lambda=2$.

#### __4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$

$\Rightarrow
\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=-12
\end{cases}
$
$\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}
$

Ответ: вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора A.