In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

#### 1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [2]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f'A:\n{A}\n')
print(f'U:\n{U}\n')
print(f'D:\n{D}\n')
print(f'V:\n{V}\n')
print(f'V.T:\n{V.T}\n')
print(f'UDV.T:\n{np.dot(np.dot(U, D), V.T)}\n')

A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]

U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]

D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]

V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]

V.T:
[[ 0.07  0.72  0.69]
 [-0.37  0.67 -0.65]
 [-0.93 -0.21  0.31]]

UDV.T:
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]



#### 2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [3]:
# а)

E_norm = D[0][0]
print(f'Trial(Euclidean norm) = {E_norm}\n')
print(f'Check(Euclidean norm) = {np.linalg.norm(A, ord=2)}\n')

Trial(Euclidean norm) = 8.824868854820442

Check(Euclidean norm) = 8.824868854820444



In [4]:
# б)

F_norm = np.sqrt(np.sum(np.power(D, 2)))
print(f'Trial(Frobenius norm) = {F_norm}\n')
print(f"Check(Frobenius norm) = {np.linalg.norm(A, ord='fro')}\n")

Trial(Frobenius norm) = 11.045361017187261

Check(Frobenius norm) = 11.045361017187261

